-- MySQL Script generated by MySQL Workbench
-- Fri Dec 15 12:14:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Phone_Number` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Phone_Number_UNIQUE` (`Phone_Number` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Address_UNIQUE` (`Address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehicle_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehicle_Type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Type_Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Type_Name_UNIQUE` (`Type_Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Vehicle_Type_id` INT NOT NULL,
  `Model` VARCHAR(45) NULL,
  `Registration_Number` VARCHAR(45) NULL,
  `Current_Kilomters` BIGINT NULL,
  `Status` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Vehicle_Vehicle_Type_idx` (`Vehicle_Type_id` ASC) VISIBLE,
  UNIQUE INDEX `Registration_Number_UNIQUE` (`Registration_Number` ASC) VISIBLE,
  CONSTRAINT `fk_Vehicle_Vehicle_Type`
    FOREIGN KEY (`Vehicle_Type_id`)
    REFERENCES `mydb`.`Vehicle_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rental_Deal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rental_Deal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Customer_id` BIGINT UNSIGNED NOT NULL,
  `Start_Rental` DATETIME NOT NULL,
  `End_Rental` DATETIME NOT NULL,
  `Rental_Dealcol` DATETIME NOT NULL,
  `Total_Cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Rental_Deal_Customer1_idx` (`Customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Rental_Deal_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `mydb`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehicle_has_Rental_Deal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehicle_has_Rental_Deal` (
  `Vehicle_id` INT NOT NULL,
  `Rental_Deal_id` INT NOT NULL,
  PRIMARY KEY (`Vehicle_id`, `Rental_Deal_id`),
  INDEX `fk_Vehicle_has_Rental_Deal_Rental_Deal1_idx` (`Rental_Deal_id` ASC) VISIBLE,
  INDEX `fk_Vehicle_has_Rental_Deal_Vehicle1_idx` (`Vehicle_id` ASC) VISIBLE,
  CONSTRAINT `fk_Vehicle_has_Rental_Deal_Vehicle1`
    FOREIGN KEY (`Vehicle_id`)
    REFERENCES `mydb`.`Vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicle_has_Rental_Deal_Rental_Deal1`
    FOREIGN KEY (`Rental_Deal_id`)
    REFERENCES `mydb`.`Rental_Deal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Start_Contract` DATETIME NOT NULL,
  `End_Contract` DATETIME NOT NULL,
  `Salary` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Position` VARCHAR(45) NOT NULL,
  `Contract_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Employee_Contract1_idx` (`Contract_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Contract1`
    FOREIGN KEY (`Contract_id`)
    REFERENCES `mydb`.`Contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Maintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Maintenance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Vehicle_id` INT NOT NULL,
  `Maintenance_Date` DATETIME NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`, `Vehicle_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Maintenance_Vehicle1_idx` (`Vehicle_id` ASC) VISIBLE,
  CONSTRAINT `fk_Maintenance_Vehicle1`
    FOREIGN KEY (`Vehicle_id`)
    REFERENCES `mydb`.`Vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Insurance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Vehicle_id` INT NOT NULL,
  `Insurence_Company` VARCHAR(45) NOT NULL,
  `PolicyNumber` INT NOT NULL,
  `Cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`, `Vehicle_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Insurance_Vehicle1_idx` (`Vehicle_id` ASC) VISIBLE,
  UNIQUE INDEX `PolicyNumber_UNIQUE` (`PolicyNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Insurance_Vehicle1`
    FOREIGN KEY (`Vehicle_id`)
    REFERENCES `mydb`.`Vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Feedback` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Rate` INT NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Rental_Deal_id` INT NOT NULL,
  `Customer_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `Rental_Deal_id`, `Customer_id`),
  UNIQUE INDEX `idFeedback_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Feedback_Rental_Deal1_idx` (`Rental_Deal_id` ASC) VISIBLE,
  INDEX `fk_Feedback_Customer1_idx` (`Customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Feedback_Rental_Deal1`
    FOREIGN KEY (`Rental_Deal_id`)
    REFERENCES `mydb`.`Rental_Deal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feedback_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `mydb`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Amount` DECIMAL(10,2) NOT NULL,
  `Payment_Date` DATETIME NOT NULL,
  `Payment_Method` VARCHAR(45) NOT NULL,
  `Rental_Deal_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Rental_Deal_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Payment_Rental_Deal1_idx` (`Rental_Deal_id` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Rental_Deal1`
    FOREIGN KEY (`Rental_Deal_id`)
    REFERENCES `mydb`.`Rental_Deal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Damage_Raport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Damage_Raport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Raport_Date` DATETIME NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Vehicle_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Vehicle_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Damage_Raport_Vehicle1_idx` (`Vehicle_id` ASC) VISIBLE,
  CONSTRAINT `fk_Damage_Raport_Vehicle1`
    FOREIGN KEY (`Vehicle_id`)
    REFERENCES `mydb`.`Vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
